import pyaudio
import yaml

cred = yaml.load(open('cred.yaml'))

MYSQL_HOST = cred['mysql_host']
MYSQL_PORT = cred['mysql_port']
MYSQL_USER = cred['mysql_user']
MYSQL_PASSWORD = cred['mysql_password']
MYSQL_DB = cred['mysql_db']
MP3_PATH = 'mp3/'
IDX_FREQ_I = 0
IDX_TIME_J = 1
DEFAULT_SAMPLING_RATE = 44100
DEFAULT_WINDOW_SIZE = 4096
DEFAULT_OVERLAP_RATIO = 0.5
DEFAULT_FAN_VALUE = 15
DEFAULT_AMP_MIN = 10
PEAK_NEIGHBORHOOD_SIZE = 20
MIN_HASH_TIME_DELTA = 0
MAX_HASH_TIME_DELTA = 200
PEAK_SORT = True
FINGERPRINT_REDUCTION = 20
DEFAULT_CHUNK_SIZE = 8192
DEFAULT_FORMAT = pyaudio.paInt16
DEFAULT_RATE = 44100
DEFAULT_CHANNELS = 2
RECORD_SECONDS = 5
DEFAULT_OUT_NAME = "OUTPUT.wav"

MATCH_STEP_LENGTH = 500
